name       : openscad
version    : 2015.03.3
release    : 6
source     :
    - https://github.com/openscad/openscad/archive/openscad-2015.03-3.tar.gz : 7816d095db9107325dd78102dd4b972c6cd931a92e28b13ff4d20425bb2c123e
license    : GPL-2.0
component  : multimedia.graphics
clang      : yes
summary    : OpenSCAD is a software for creating solid 3D CAD objects
description: |
    OpenSCAD is a software for creating solid 3D CAD objects
builddeps  :
    - pkgconfig(eigen3)
    - pkgconfig(fontconfig)
    - pkgconfig(glew)
    - pkgconfig(harfbuzz)
    - pkgconfig(Qt5Widgets)
    - pkgconfig(Qt5UiTools)
    - CGAL-devel
    - libboost-devel
    - opencsg-devel
    - qscintilla-devel
setup      : |
    %patch -p1 -l < $pkgfiles/qt5_gettext.patch
    %qmake QMAKE_CFLAGS_ISYSTEM=-I PREFIX=/usr
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
