name       : openscad
version    : 2015.03
release    : 1
source     :
    - https://github.com/openscad/openscad/archive/openscad-2015.03.tar.gz : 7c7f92b3d95e1ed75fcc0615dfc5953a2e3427b71051973db78afcb876c9db31
license    : GPL-2.0
component  : multimedia.graphics
summary    : OpenSCAD is a software for creating solid 3D CAD objects
description: |
    OpenSCAD is a software for creating solid 3D CAD objects
builddeps  :
    - pkgconfig(eigen3)
    - pkgconfig(glew)
    - pkgconfig(harfbuzz)
    - pkgconfig(QtCore)
    - CGAL-devel
    - libboost-devel
    - opencsg-devel
    - qscintilla-devel
setup      : |
    qmake-qt4 QMAKE_CFLAGS_ISYSTEM=-I \
              QMAKE_MOC=/usr/bin/moc-qt4 \
              QMAKE_RCC=/usr/bin/rcc-qt4 \
              QMAKE_UIC=/usr/bin/uic-qt4 \
              QMAKE_CXXFLAGS="$CXXFLAGS" \
              PREFIX=/usr \
              -r openscad.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
